### ISSUE TITLE
Intentos Restantes

### ISSUE THREAD

**Issue by angelsimon** [Jonatandb/Codebreaker_SDL1#6]
En ambas versiones de CodeBlocks, la cantidad de intentos restantes siempre es 1. (Ejecutado desde Wine)

![captura de pantalla de 2016-06-20 21-55-49](https://cloud.githubusercontent.com/assets/627054/16214742/cb6ceaf0-3731-11e6-8db4-9a1a0b06b555.png)

**Comment by Jonatandb** [comment]
Relacionado con esto:

![segmentationfault](https://cloud.githubusercontent.com/assets/8082172/16214989/4c149e08-3734-11e6-8568-1024b751f743.PNG)

**Comment by Jonatandb** [comment]
Solucionado, por copiar y pegar cuando estuve reemplazando las llamadas a "to_string()", dejé en esta clase código que había copiado desde otra donde ya había hecho los reemplazos mencionados.
